-- =====================================================================
--  Sistema de Gestão de Estágios — Belo Horizonte
--  Banco de dados (Supabase / PostgreSQL)
--
--  Mesmo projeto Supabase usado pelo sistema de São Paulo.
--  As tabelas de BH usam o sufixo _bh (SP usa _sp), então os dois
--  sistemas convivem sem conflito.
--
--  COMO USAR:
--  1. Acesse https://supabase.com e abra o projeto.
--  2. Menu lateral  ->  SQL Editor  ->  New query.
--  3. Cole TODO este arquivo e clique em RUN.
--  Pode rodar novamente sem problema (é idempotente).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Tabela: campos_bh  (cadastro dos campos de estágio)
-- ---------------------------------------------------------------------
create table if not exists public.campos_bh (
  id            bigint generated by default as identity primary key,
  nome          text    not null,
  endereco      text    default '',
  cidade        text    default '',
  curso         text    default 'enfermagem',      -- enfermagem | radiologia | ambos
  status        text    default 'ativo',           -- ativo | inativo
  vagas         jsonb   default '{"M":0,"T":0,"N":0,"S":0,"D":0}'::jsonb, -- vagas por período
  alternado     boolean default false,             -- trabalha com PAR/ÍMPAR (3x2)
  compartilhado boolean default false,             -- dividido entre 2 unidades
  preceptor     boolean default false,
  contra        text    default 'sem',             -- hora | mensal | fixo | edc | sem
  valor         numeric default 0,
  contatos      jsonb   default '[]'::jsonb,        -- [{nome, telefone, email}, ...]
  docs          jsonb   default '[]'::jsonb,        -- ["Vacinação", "Seguro", ...]
  horarios      jsonb   default '{}'::jsonb,        -- {"M":["07:00","13:00"], ...}
  obs           text    default '',
  utilizado     boolean default false,             -- já foi usado (bloqueia exclusão)
  created_at    timestamptz default now()
);

-- ---------------------------------------------------------------------
-- Tabela: alocacoes_bh  (distribuição das turmas nos campos)
-- ---------------------------------------------------------------------
create table if not exists public.alocacoes_bh (
  id           bigint generated by default as identity primary key,
  campo_id     bigint references public.campos_bh(id) on delete cascade,
  unidade      text    default '',
  turma        text    default '',
  curso        text    default 'enfermagem',       -- enfermagem | radiologia
  competencia  text    default '',                 -- 'AAAA-MM' (ex.: 2026-08)
  modelo       text    default 'semana_todos',     -- semana_todos | semana_3x2 | fds_sabdom | fds_sab | fds_dom
  semana       text    default '',                 -- par | impar | '' (só no 3x2)
  turnos       jsonb   default '[]'::jsonb,         -- ["M"] ou ["M","T"]
  alunos       integer default 0,
  data_ini     date,
  data_fim     date,
  created_at   timestamptz default now()
);

create index if not exists alocacoes_bh_campo_idx on public.alocacoes_bh (campo_id);
create index if not exists alocacoes_bh_comp_idx  on public.alocacoes_bh (competencia);

-- ---------------------------------------------------------------------
-- Segurança (RLS) — libera acesso com a chave pública do projeto.
-- (Ferramenta interna; mesmo modelo já usado nas tabelas _sp.)
-- ---------------------------------------------------------------------
alter table public.campos_bh    enable row level security;
alter table public.alocacoes_bh enable row level security;

drop policy if exists "campos_bh_acesso"    on public.campos_bh;
drop policy if exists "alocacoes_bh_acesso" on public.alocacoes_bh;

create policy "campos_bh_acesso"    on public.campos_bh    for all using (true) with check (true);
create policy "alocacoes_bh_acesso" on public.alocacoes_bh for all using (true) with check (true);

-- Privilégios para os papéis usados pela chave pública
grant all on public.campos_bh, public.alocacoes_bh to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
